### ISSUE TITLE
"Unknown RepositoryDefinition"

### ISSUE THREAD

**Issue by RangerRick** [HackAttack/bamboo-github-status#16]
I tried enabling this add-on in my Bamboo instance, and I'm getting failures like this:

```
java.lang.IllegalArgumentException: Unknown RepositoryDefinition 167477355
	at com.atlassian.bamboo.v2.build.BuildChangesImpl.getBuildRepositoryChanges(BuildChangesImpl.java:211)
	at com.atlassian.bamboo.v2.build.BuildChangesImpl.getVcsRevisionKey(BuildChangesImpl.java:65)
	at com.mhackner.bamboo.AbstractGitHubStatusAction.updateStatus(AbstractGitHubStatusAction.java:54)
	at com.mhackner.bamboo.GitHubStatusPostStage.execute(GitHubStatusPostStage.java:30)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$6.call(ChainPluginSupportImpl.java:203)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$6.call(ChainPluginSupportImpl.java:199)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$2.call(ChainPluginSupportImpl.java:113)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$2.call(ChainPluginSupportImpl.java:108)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:132)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:107)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.access$000(ChainPluginSupportImpl.java:45)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.run(ChainPluginSupportImpl.java:95)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:206)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:33)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:90)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.stageCompleted(ChainPluginSupportImpl.java:198)
	at sun.reflect.GeneratedMethodAccessor2572.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy178.stageCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$4.run(ChainExecutionManagerImpl.java:758)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:693)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:123)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:484)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:465)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:448)
	at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:51)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
	at java.lang.Thread.run(Thread.java:745)
```

Since there doesn't seem to be much I can do configuration-wise, I'm not clear what I could do to fix this.  Any ideas?

**Comment by RangerRick** [comment]
Oop, looks like the user we access github as didn't have the rights to see one of the particular repos it was attempting to update.  Never mind.  :)
