### ISSUE TITLE
Plugin Breaks with Bamboo 5.15.0.1

### ISSUE THREAD

**Issue by RangerRick** [HackAttack/bamboo-github-status#21]
```
java.lang.NoSuchMethodError: com.atlassian.bamboo.plugins.git.GitHubRepository.getEncryptedPassword()Ljava/lang/String;
        at com.mhackner.bamboo.AbstractGitHubStatusAction.setStatus(AbstractGitHubStatusAction.java:89)
        at com.mhackner.bamboo.AbstractGitHubStatusAction.updateStatus(AbstractGitHubStatusAction.java:57)
        at com.mhackner.bamboo.GitHubStatusPreStage.execute(GitHubStatusPreStage.java:22)
```

**Comment by HackAttack** [comment]
Apparently this module is not considered part of Bamboo’s public API: https://jira.atlassian.com/browse/BAM-18188
