### ISSUE TITLE
"null" from c.m.b.Configuration when using Repository Stored Specs

### ISSUE THREAD

**Issue by emzeidan** [HackAttack/bamboo-github-status#34]
### Summary
When running Repository Stored Specs from GitHub, the Bamboo Plan cannot be created because of a null that is passed from Configuration.java

### Steps to reproduce

1. Upgrade to Bamboo 6.5 or above
2. Ensure the latest version of the `bamboo-github-status` plugin is installed
3. Link a GitHub repository to Bamboo
4. Create a simple Repository Stored Specs using YAML
5. Commit a change to your Specs
6. Look at the Specs Status

### Expected Behavior
Bamboo Specs runs successfully and the Plan is created

### Actual Behavior
The following appears in the Specs Status error log:
```There was an error when processing yaml file "bamboo.yaml". File structure is correct, contact Atlassian Support for assistance on resolving this issue.

Could not parse key 'null'
java.lang.IllegalArgumentException: Could not parse key 'null'
	at com.atlassian.bamboo.plan.PlanKeys.getPlanKey(PlanKeys.java:244)
	at com.mhackner.bamboo.Configuration.addDefaultValues(Configuration.java:53)
	at com.atlassian.bamboo.configuration.external.helpers.BuildConfigurationPluginsExportHelper.lambda$addDefaultValues$2(BuildConfigurationPluginsExportHelper.java:36)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
... 
```

From the Stack trace, I was able to find that the issue was coming from `c.m.b.Configuration#addDefaultValues()`. The only workaround for now is to Disable the `bamboo-github-status` Plugin.

### Note + Disclaimer
This issue was reported via Atlassian Support, and I am the Support Engineer for Bamboo on the ticket

**Comment by emzeidan** [comment]
Update: Looks like this would be fixed by PR #33 🙂
